# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
import numpy as np
a = np.arange(10)
b = a.reshape(2, 5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
a = np.arange(10).reshape(2,5)
b = np.ones((2,5),dtype= "int32")
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [9]:
c = np.arange(10).reshape(2,5)
d = np.ones((2,5),dtype = "int32")
np.hstack((c,d))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
e = np.arange(10).reshape(5,2)
e.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [11]:
f = np.arange(15).reshape(5,3)
f.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [12]:
e = np.arange(15)
e.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [13]:
g = np.arange(25).reshape(5,5)
g**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [14]:
h = np.arange(30).reshape(5,6)
np.mean(h)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [15]:
i = np.arange(30).reshape(5,6)
np.std(i)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [16]:
j = np.arange(30).reshape(5,6)
np.median(j)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [17]:
j.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [18]:
k = np.arange(16).reshape(4,4)
k.trace()


30

## Question:13

### Find the determinant of the previous array in Q12?

In [19]:
l = np.arange(16).reshape(4,4)
np.linalg.det(l)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [20]:
m = np.arange(30).reshape(5,6)
print(np.percentile(m,5))
print(np.percentile(m,95))

1.4500000000000002
27.549999999999997


## Question:15

### How to find if a given array has any null values?

In [21]:
n = np.arange(30).reshape(5,6)
np.isnan(n)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])